version: '3.8'

services:
  music-streaming-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-streaming
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - API_BASE_URL=${API_BASE_URL}
      - PROXY_TARGET_URL=${PROXY_TARGET_URL}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - GENIUS_ACCESS_TOKEN=${GENIUS_ACCESS_TOKEN}
    restart: unless-stopped
    networks:
      - music-streaming-network

networks:
  music-streaming-network:
    driver: bridge
